### ISSUE TITLE
Missing run-server.sh referenced in microexample Makefile

### ISSUE THREAD

**Issue by jbweeks** [joshcough/MinecraftPlugins#5]
I'm trying to work on our first Minecraft Mod with my 10 year-old in Scala, and found your repo. Thanks for contributing!

Anyway, I stumbled into the microexample, but it seems to be missing the run-server.sh script.

Also, the artifactoryonline.com repo referenced in the Makefile no longer seems to host the sbt-launch.jar, but I found one here: http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar

Thanks again, and looking forward to using your Plugins and API.

**Comment by jbweeks** [comment]
This is arguably covered in "built on Bukkit" mentioned in the ReadMe, but for other Minecraft mod noobs such as myself, here are the steps I took to get things working on a mac (Linux will be similar):

1. Download Bukkit (e.g. from: http://tcpr.ca/craftbukkit, or wherever you can find it)
2. Copy the jar you downloaded to e.g. microexample/bukkit (or wherever you are going to run it from -- one level above your relevant plugins directory)
3. Create a script to launch, e.g. *touch run-server.sh*, and make it executable, *chmod +x run-server.sh*
4. Add the following content in the scriptj (using the jar name you downloaded in #2 above):
````
     #!/bin/bash
     java -Xmx1024M -jar craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar -o true
````
5. Run the script once (e.g. ./run-server.sh) from the directory where it lives (e.g. microexample/bukkit)
6. (It will probably fail once the eula.txt), if so then edit the eula.txt and change "false" to "true"
7. At this point, it worked for me, YMMV
8. profit!

**Comment by joshcough** [comment]
I'm sorry I was unable to help you on this. I had spine surgery at the beginning of the month. I'm really glad that you have it working. Do you want to package up what you've done into a PR of some sort?

I haven't touched this in a really long time, so, updating things to latest versions (like I see  you have with bukkit) would be awesome.
